CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS "restaurant"(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    cuisine VARCHAR NOT NULL,
    average_cost INT NOT NULL,
    ranting DECIMAL(2,1),
    votes INT,
    embedding vector(1536)
);

CREATE TABLE IF NOT EXISTS "order"(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    order_date TIMESTAMP(6) NOT NULL,
    total_amount INT NOT NULL,
    rating DECIMAL(2,1),

    CONSTRAINT fk_order_restaurant
        FOREIGN KEY (restaurant_id) REFERENCES restaurant(id)
);

CREATE INDEX IF NOT EXISTS idx_restaurant_embedding_vector_hnsw
ON "restaurant"
USING hnsw (embedding vector_cosine_ops);